#!/usr/bin/env bash
# capture.sh - Capture session context for continuity
# Usage: ./scripts/capture.sh [session_name]

set -e

SESSION_NAME="${1:-$(date +%Y-%m-%d)_session}"
OUTPUT_DIR="docs/sessions"
OUTPUT_FILE="$OUTPUT_DIR/${SESSION_NAME}_context.md"

echo "Capturing session context..."
echo ""

# Create output directory if needed
mkdir -p "$OUTPUT_DIR"

# Start capture
cat > "$OUTPUT_FILE" << EOF
# Session Context Capture

**Captured**: $(date +"%Y-%m-%d %H:%M:%S")
**Session**: $SESSION_NAME

## Git Status

\`\`\`
$(git status 2>/dev/null || echo "Not a git repository")
\`\`\`

## Current Branch

\`\`\`
$(git branch --show-current 2>/dev/null || echo "Unknown")
\`\`\`

## Recent Commits

\`\`\`
$(git log --oneline -10 2>/dev/null || echo "No commits")
\`\`\`

## Modified Files

\`\`\`
$(git diff --name-only 2>/dev/null || echo "None")
\`\`\`

## Environment

- Python: $(python3 --version 2>&1 || echo "Not found")
- Working Directory: $(pwd)
- User: $(whoami)

## Project Structure (Top Level)

\`\`\`
$(ls -la 2>/dev/null | head -20)
\`\`\`

---
*Generated by scripts/capture.sh*
EOF

echo "Context captured to: $OUTPUT_FILE"
echo ""
cat "$OUTPUT_FILE"
